# Generated by Django 3.2.5 on 2021-07-14 20:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0002_auto_20210707_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locations', models.CharField(choices=[('L’Île-Bizard—Sainte-Geneviève', 'L’Île-Bizard—Sainte-Geneviève'), ('Pierrefonds-Roxboro', 'Pierrefonds-Roxboro'), ('Saint-Laurent', 'Saint-Laurent'), ('Ahuntsic-Cartierville', 'Ahuntsic-Cartierville'), ('Montréal-Nord', 'Montréal-Nord'), ('Rivière-des-Prairies—Pointe-aux-Trembles', 'Rivière-des-Prairies—Pointe-aux-Trembles'), ('Anjou', 'Anjou'), ('Saint-Léonard', 'Saint-Léonard'), ('Villeray—Saint-Michel—Parc-Extension', 'Villeray—Saint-Michel—Parc-Extension'), ('Rosemont—La Petite-Patrie', 'Rosemont—La Petite-Patrie'), ('Mercier—Hochelaga-Maisonneuve', 'Mercier—Hochelaga-Maisonneuve'), ('Le Plateau-Mont-Royal', 'Le Plateau-Mont-Royal'), ('Outremont', 'Outremont'), ('Ville-Marie', 'Ville-Marie'), ('Côte-des-Neiges—Notre-Dame-de-Grâce', 'Côte-des-Neiges—Notre-Dame-de-Grâce'), ('Le Sud-Ouest', 'Le Sud-Ouest'), ('Verdun', 'Verdun'), ('LaSalle', 'LaSalle')], max_length=50)),
                ('organization_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('service_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('organization_type', models.CharField(choices=[('sustainable restaurant', 'sustainable restaurant'), ('educate and assist children', 'educate and assist children'), ('restaurant/catering service', 'restaurant/catering service'), ('food insecurity', 'food insecurity'), ('food insecurity and autonomy', 'food insecurity and autonomy'), ('food insecurity and women', 'food insecurity and women'), ('food insecurity and homeless', 'food insecurity and homeless'), ('community services', 'community services'), ('community services - youth', 'community services - youth'), ('various community services', 'various community services')], max_length=50)),
                ('roles', multiselectfield.db.fields.MultiSelectField(choices=[('clean', 'Clean'), ('cook', 'Cook'), ('serve', 'Serve'), ('prep', 'Prep'), ('garden', 'Garden'), ('delivery', 'Delivery'), ('education', 'Education'), ('warehouse', 'Warehouse'), ('daycare', 'Day care'), ('sort', 'Sort')], max_length=60)),
            ],
        ),
    ]
